name: Scheduling Test
on:
  schedule:
  - cron: '30 5 * * 1,3' # 월, 수 오전  5시30분에 실행 한국시간(KST 14:30)
  - cron: '30 5 * * 2,4' # 화, 목 오전  5시30분에 실행 한국시간(KST 14:30)
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Not on Monday or Wednesday
      if: github.event.schedule != '30 5 * * 1,3' # 해당 조건이 아닐때만 실행됨 결국 화 목 오전 5시 30분에만 실행
      run: echo "This step will be skipped on Monday and Wednesday"
    - name: Every time
      run: echo "Time step will always run"
